# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        # name our filter set "my_thumb_filter"
        fixed_filter_thumb:
            filters:
                # use and setup the "fixed" filter
                fixed:
                    width: 360
                    height: 180
        fixed_filter_small:
            filters:
                # use and setup the "fixed" filter
                fixed:
                    width: 480
                    height: 240
        fixed_filter_big:
            filters:
                # use and setup the "fixed" filter
                fixed:
                    width: 640
                    height: 320


