neo4j:
    profiling:
        enabled: true
    connections:
        default:
            scheme: http # default (must be either "http" or "bolt")
            host: localhost # default
            port: # optional, will be set to the proper driver's default port if not provided
            username: neo4j # default
            password: supersecret # default
    clients:
        default:
            connections: [default]

